# Auto-generated by transterpreter.py

def _try_convert(val):
    try:
        return int(val)
    except ValueError:
        try:
            return float(val)
        except ValueError:
            return val

def Helper(x):
    return x * 2
def Main():
    print(Helper(3))

if __name__ == '__main__':
    Main()
